### PR TITLE
Added a view

### PR DESCRIPTION
**Pull request by DaFa66**
Thought a view might be handy

### CODE REVIEW

**Comment by DaFa66** [comment]
A view is an HTML document, and looking up Google > Is it necessary to write doctype in HTML?

> "All HTML need to have a DOCTYPE declared. The DOCTYPE is not actually an element or HTML tag. It lets the browser know how the document should be interpreted, by indicating what version or standard of HTML (or other markup languages) is being used."

I had the same idea of having a drop-down to choose if you want a view with or without a template.  Maybe we chat about on Skype.  I don't think it makes the extension more complicated if anything it makes you faster with a boilerplate at your finger tips.

**Review by jakecastelli — APPROVED** [review]
I will merge this with the additional popup (maybe implementing next week).

Also, thinking when the user presses enter button, we directly open the controller file.

**Comment by DaFa66** [comment]
Sounds good, but was thinking you were right about using a template with
the view. Do you think we could implement a template with the currently
selected CSS framework or one of ours, keeping it simple?

**Comment by jakecastelli** [comment]
Good idea, we could have a simple template of ours.

**Review by jakecastelli — APPROVED** [review]
It was under #8, but all it is well 👍

**Pull request merged**
